config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :produce_orders
  devise_for :users
  resources :moving_jobs

  root "moving_jobs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/moving_job.rb
class MovingJob < ApplicationRecord
  validates_format_of :customer_email, with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/

  STATES = [
    ["Massachusetts", "MA"],
    ["New Hampshire", "NH"],
    ["Connecticut", "CT"],
    ["Maine", "ME"]
  ]
end

app/models/produce_order.rb
class ProduceOrder < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /customers/1
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /customers/1
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def customer_params
      params.fetch(:customer, {})
    end
end

app/controllers/moving_jobs_controller.rb
class MovingJobsController < ApplicationController

  def index
    @all_jobs = MovingJob.all
  end

  def show
    @moving_job = MovingJob.find(params[:id])
  end

  def new
    @moving_job = MovingJob.new
    @state_collection = MovingJob::STATES
  end

  def create
    @moving_job = MovingJob.new(moving_job_params)

    if @moving_job.save
      MovingFormMailer.new_moving_job(@moving_job).deliver_later
      redirect_to @moving_job, notice: 'Thank you! Your moving job inquiry was successfully submitted.'
    else
      render :new
    end
  end

  def edit
    @moving_job = MovingJob.find(params[:id])
  end

  private

  def moving_job_params
    params.require(:moving_job).permit(
      :customer_name,
      :customer_email,
      :customer_phone_no,
      :customer_street_address,
      :customer_town,
      :customer_state,
      :customer_zipcode,
      :customer_message,
      :date_of_move,
      :estimated_amount_of_hours,
      :requested_amount_of_movers,
      :new_customer_address,
      :new_customer_town,
      :new_customer_state,
      :new_customer_zipcode,
    )
  end
end

app/controllers/produce_orders_controller.rb
class ProduceOrdersController < ApplicationController
  before_action :set_produce_order, only: [:show, :edit, :update, :destroy]

  # GET /produce_orders
  def index
    @produce_orders = ProduceOrder.all
  end

  # GET /produce_orders/1
  def show
  end

  # GET /produce_orders/new
  def new
    @produce_order = ProduceOrder.new
  end

  # GET /produce_orders/1/edit
  def edit
  end

  # POST /produce_orders
  def create
    @produce_order = ProduceOrder.new(produce_order_params)

    if @produce_order.save
      redirect_to @produce_order, notice: 'Produce order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /produce_orders/1
  def update
    if @produce_order.update(produce_order_params)
      redirect_to @produce_order, notice: 'Produce order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /produce_orders/1
  def destroy
    @produce_order.destroy
    redirect_to produce_orders_url, notice: 'Produce order was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produce_order
      @produce_order = ProduceOrder.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def produce_order_params
      params.fetch(:produce_order, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/moving_jobs_helper.rb
module MovingJobsHelper
end

app/helpers/produce_orders_helper.rb
module ProduceOrdersHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/_footer.html.erb
  <div class="footer-left">

    <h3>Company<span>logo</span></h3>


    <p class="footer-links">
      <a href="#">Produce</a>
      ·
      <%= link_to 'Moving & Storage', moving_jobs_path %>
      ·
      <a href="#">Consignments</a>
    </p>

    <p class="footer-company-name">FANCYS ENTERPRISES LTD &copy; 1986</p>

    <div class="footer-icons">

      <a href="https://www.facebook.com/pages/Fancys-Produce/156901187850025?fref=ts"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="https://www.linkedin.com/in/ron-fancy-aa510049"><i class="fa fa-linkedin"></i></a>
      <a href="#"><i class="fa fa-github"></i></a>

    </div>
  </div>

  <div class="footer-center">
    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>PO Box 249</span>East Orleans, MA 02643</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>Ph: (508) 255-1902</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>Cell: (508) 967-4072</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>Fax: (508) 240-3526</p>
    </div>

    <div>
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:ron@fancys.us">ron@fancys.us</a></p>
    </div>

  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>Ron Fancy · Owner/President</span>
      Fancy Enterprises has been serving the Cape Cod area for over 30 years. We provide high quality fruits and vegetables to local retail businesses and restaurants, and offer a full service moving compant that specializes in small moving jobs.
    </p>

  </div>

app/views/layouts/_header.html.erb
<div class="header-limiter">
  <h1><a href="#">Company<span>logo</span></a></h1>

  <nav>
    <a href="#">Produce</a>
    <a href="#">Moving & Storage</a>
    <a href="#">Consignments</a>
  </nav>

  <% if user_signed_in? %>
    <ul>
      <li><%= link_to 'Edit Your Account', edit_user_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, :method=>'delete' %></li>
    </ul>
    <% else %>
    <ul>
      <li><%= link_to 'Sign in', new_user_session_path %></li>
      <li><%= link_to 'Register', new_user_registration_path %></li>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Fancys Enterprises LTD" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header class="header-login-signup">
      <%= render "layouts/header" %>
    </header>

    <div class="content">
      <%= yield %>
    </div>

    <footer class="footer-distributed">
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/moving_jobs/_form.html.erb
<%= form_for(@moving_job) do |f| %>
  <% if @moving_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moving_job.errors.count, "error") %> prohibited this moving job from being submitted:</h2>

      <ul>
      <% @moving_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name %>
  </div>

  <div class="row">
    <%= f.label :customer_email %>
    <%= f.text_field :customer_email %>
  </div>

  <div class="row">
    <%= f.label :customer_phone_no, "Full Name" %>
    <%= f.text_field :customer_phone_no %>
  </div>

  <h4>Where are you moving from?</h4>

  <div class="row">
    <%= f.label :customer_street_address, "Street Address" %>
    <%= f.text_field :customer_street_address %>
  </div>

  <div class="row">
    <%= f.label :customer_town, "Town" %>
    <%= f.text_field :customer_town %>
  </div>

  <div class="row">
    <%= f.label :customer_state, "State" %>
    <%= f.select(:customer_state, @state_collection, {include_blank: true}) %>
  </div>

  <div class="row">
    <%= f.label :customer_zipcode, "Zipcode" %>
    <%= f.text_field :customer_zipcode %>
  </div>

  <h4>Where are you moving to?</h4>

  <div class="row">
    <%= f.label :new_customer_address, "Street Address" %>
    <%= f.text_field :new_customer_address %>
  </div>

  <div class="row">
    <%= f.label :new_customer_town, "Town" %>
    <%= f.text_field :new_customer_town %>
  </div>

  <div class="row">
    <%= f.label :new_customer_state, "State" %>
    <%= f.select(:new_customer_state, @state_collection, {include_blank: true}) %>
  </div>

  <div class="row">
    <%= f.label :new_customer_zipcode, "Zipcode" %>
    <%= f.text_field :new_customer_zipcode %>
  </div>

<h4>Additional Information</h4>

  <div class="row">
    <%= f.label :date_of_move, "Date of Move" %>
    <%= f.text_area :date_of_move %>
  </div>

  <div class="row">
    <%= f.label :estimated_amount_of_hours, "How many hours do you estimate the move taking?" %>
    <%= f.text_field :estimated_amount_of_hours %>
  </div>

  <div class="row">
    <%= f.label :requested_amount_of_movers, "How many movers do you estimate needing?" %>
    <%= f.text_field :requested_amount_of_movers %>
  </div>

  <div class="row">
    <%= f.label :customer_message, "Is there anything else you would like to specify about the move?" %>
    <%= f.text_area :customer_message %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Moving Inquiry" %>
  </div>
<% end %>

app/views/moving_jobs/index.html.erb
<h1>Fancy's Moving & Storage</h1>

<% if @all_jobs %>
  <% @all_jobs.each do |job| %>
    <%= link_to job.customer_name, moving_job_path(job) %>
  <% end %>
<% end %>
<%= link_to "Submit a Moving Inquiry", new_moving_job_path %>

app/views/moving_jobs/new.html.erb
<h1>New Moving Job</h1>

<%= render 'form' %>

<%= link_to 'Back', moving_jobs_path %>

app/views/moving_jobs/show.html.erb
<%= @moving_job.customer_name %>
<%= @moving_job.customer_email %>
<%= @moving_job.customer_phone_no%>
<%= @moving_job.customer_street_address %>
<%= @moving_job.customer_town %>
<%= @moving_job.customer_state %>
<%= @moving_job.customer_zipcode %>
<%= @moving_job.customer_message %>
<%= @moving_job.date_of_move %>
<%= @moving_job.estimated_amount_of_hours %>
<%= @moving_job.requested_amount_of_movers %>
<%= @moving_job.new_customer_address %>
<%= @moving_job.new_customer_town %>
<%= @moving_job.new_customer_state %>
<%= @moving_job.new_customer_zipcode %>

app/views/produce_orders/_form.html.erb
<%= form_for(produce_order) do |f| %>
  <% if produce_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produce_order.errors.count, "error") %> prohibited this produce_order from being saved:</h2>

      <ul>
      <% produce_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produce_orders/edit.html.erb
<h1>Editing Produce Order</h1>

<%= render 'form', produce_order: @produce_order %>

<%= link_to 'Show', @produce_order %> |
<%= link_to 'Back', produce_orders_path %>

app/views/produce_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produce Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produce_orders.each do |produce_order| %>
      <tr>
        <td><%= link_to 'Show', produce_order %></td>
        <td><%= link_to 'Edit', edit_produce_order_path(produce_order) %></td>
        <td><%= link_to 'Destroy', produce_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produce Order', new_produce_order_path %>

app/views/produce_orders/new.html.erb
<h1>New Produce Order</h1>

<%= render 'form', produce_order: @produce_order %>

<%= link_to 'Back', produce_orders_path %>

app/views/produce_orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_produce_order_path(@produce_order) %> |
<%= link_to 'Back', produce_orders_path %>